from langchain_community.document_loaders import TextLoader
loader = TextLoader("data/company_policy.txt")
documents = loader.load()
print(type(documents))
print(documents)
print(len(documents))
print(type(documents[0]))
print(documents[0].page_content)
print(documents[0].metadata)
print(documents[0])
